### ISSUE TITLE
Zero X Y Button

### ISSUE THREAD

**Issue by rodw-au** [phillc54/qtplasmac#13]
Could we have a button that zeroes the current coordinate system on both the X & Y axes? I know you can do this with the DRO's for individual axes but this isn't a mill where you want to touch off individually, Normally you want to position the torch somewhere and make that the 0,0 origin.

There seems to be enough room between the home all and G54 buttons to place this feature.
Alternatively add an option to the coordinate system menu popup to "Zero XY"

This is much faster than the Gmoccapy touch off but it would be nice if you only had to do one, not two operations.

**Comment by phillc54** [comment]
You will be able to do that on the user buttons.

**Comment by rodw-au** [comment]
Remember you said they were next!

**Comment by phillc54** [comment]
There isnow a bonus touchoff xy button for you.

**Comment by rodw-au** [comment]
Great, confirned work but I just had an awful thought. Where does the DRO go if someone adds a rotary axis? Ooops.

**Comment by phillc54** [comment]
x and y are not rotary, a or b would be.
There is provision for four axes but not tested yet.

**Comment by rodw-au** [comment]
I was thinking that we may have unwittingly used the slot for the A axis DRO....

**Comment by phillc54** [comment]
Nah, it goes to the bottom and the others push up.

**Comment by rodw-au** [comment]
Cool, I think we can close this then.
