### ISSUE TITLE
qtplasmac.tcl is not loaded by the ini file

### ISSUE THREAD

**Issue by rodw-au** [phillc54/qtplasmac#3]
Without this being loaded, no values are sent to plasmac.comp so required paremeters (eg feedrate) are missing so the program will not run

**Comment by rodw-au** [comment]
I loaded this as a POST_GUI file, not sure of convention but it worked!

**Comment by phillc54** [comment]
I haven't seen this issue, I'll check it out tomorrow.

**Comment by phillc54** [comment]
It should be loaded from the [DISPLAY] section:

DISPLAY = qtvcp -c qtplasmac -H qtplasmac/qtplasmac.tcl -u qtplasmac/qtplasmac_handler.py qtplasmac_16x9

**Comment by rodw-au** [comment]
Hmm, deleted my postgui and it seems to be working now. I think it needs a leading . in the path. eg

`./qtplasmac/qtplasmac.tcl`

**Comment by phillc54** [comment]
Strange, it works here as is on both Stretch and Buster

**Comment by rodw-au** [comment]
So I pulled it down into a new folder and it worked first time. I guess you can close this issue. My view is that any sub folder should be prefaced by a ./ to denote to start at the current working directory to avoid any confusion which clearly I had initially. 

Good  to see you have  materials file now. So I think I could try it out on a real machine. How would I do that? Just copy my connections.hal file and material file into the folder? I'll be compiling from source so I might need some prerequisites do you think!

**Comment by phillc54** [comment]
No material file yet, just the default material. I am almost finished adding the material file maybe tomorrow.

**Comment by rodw-au** [comment]
CLOSED
