### ISSUE TITLE
Cut feedrate not initialised in qtplasmac.prefs file

### ISSUE THREAD

**Issue by rodw-au** [phillc54/qtplasmac#4]
This also threw me for a while. With a zero value here, gcode will not run.

**Comment by phillc54** [comment]
Nor should it. :-)
 It does throw up an error but they are a bit hidden at the moment.

**Comment by rodw-au** [comment]
While its just a sim, it really needs something here so people can cut the famous spanner!

**Comment by phillc54** [comment]
Haha, I'll get on it.

**Comment by rodw-au** [comment]
I'll just test now and again seeing I'm organised to update and update any issues I see here :)

**Comment by phillc54** [comment]
I haven't updated for a several days, been a bit busy with some home duties. There should be a lot of errors as there is a lot of work still to be done.
I "think" you could actually cut with it as long as the default material setting were correct.
