### ISSUE TITLE
gcode filter program needs python3 shebang

### ISSUE THREAD

**Issue by c-morley** [phillc54/qtplasmac#5]

**Comment by c-morley** [comment]
After that is fixed - it complains: No such file or directory: 'qtplasmac_material.cfg'

**Comment by phillc54** [comment]
I fixed the material file issue.
The python2/3 thing confuses me, at the moment I have it working on python2 (stretch + lcnc 2.8 + python2) and python3 (buster + lcnc master + python3) with the python shebang. If I change that to python3 then how do I get it to work with python2 or should I just forget python2 and only use buster and use the python3 shebang in all python files.

**Comment by c-morley** [comment]
Sorry I thought you were targeting python3 only.
Python3 support is still lacking a bit for GTK stuff but does seem to work otherwise.
My qt5 is too old on my python2 system for some functions you use -I'll try again with a newer version.

I'm not experienced with shebang or python 2/3 conversion (making it up as I go)
If you want to support both you could always supply two versions of the file but there has got to be a better way.
I'll take a look.

**Comment by phillc54** [comment]
I was targeting python3 but while it worked on python 2 as well I was happy.
It is probably best to cut ties to python2, no point in making life harder than necessary.

**Comment by c-morley** [comment]
So far I have qtvcp supporting both (I fix python3 bugs as I find them)
It's the strings vrs bytes that is a pain.
But ultimately 2.9 will be python3.
If you wish to use the screen with 2.8 then you will need to cover python2

I would of course love to add your code, when you are ready to linuxcnc if that makes it easier to have people test/develoip.

**Comment by c-morley** [comment]
i just re read your first post - interesting - I used buster and the original shebang picked up the wrong python version.
I'll look into that - maybe it's just on my end.

**Comment by phillc54** [comment]
I have the default python set to 3 on my buster vm and 2 on my stretch vm and so far it has worked on both.
I think if ends up requiring two different versions I will be tempted to just go with 2.9. (a bit selfish but...)
Most plasma guys wouldn't have a problem going to 2.9 if they want to use this gui (I hope)
I was going to ask you about moving it to the usual place for qtvcp screens when I get it completed.

**Comment by rodw-au** [comment]
I'm using Python 2.9 compiled here. I think there will be some more features added to 2.9 that Plasmac could use so I think this should be a 2.9 only screen. Lets face it, we used to have to pull from Phill's repo to get Plasmac.

**Comment by phillc54** [comment]
python will determine that, if it runs on python2 & python3 then it will be usable on 2.8. If it only runs on python3 then I don't think I will be bothered to have a different version for python2.

What python version are you running?
