### ISSUE TITLE
M190 raises error (Gcode does not exist)

### ISSUE THREAD

**Issue by rodw-au** [phillc54/qtplasmac#6]
Just pulled down one of my cut files. Its not from one of the latest SHeetcam posts, but this stops us in our tracks. File attached.
V2.9 compiled in the last few days...
[laser bracket-6mm.ngc.txt](https://github.com/phillc54/qtplasmac/files/5541930/laser.bracket-6mm.ngc.txt)

**Comment by phillc54** [comment]
Fixed

**Comment by rodw-au** [comment]
Cool, So I should be able to cut something with this then? Probably try that next weekend as won't have much time to play before then!

**Comment by phillc54** [comment]
I "think" so, bearing in mind that here are no user buttons yet nor is there any cut-recovery/reverse-run

**Comment by rodw-au** [comment]
I was never able to work out reverse run or cut recovery so I don't need them yet
User buttons would be nice so I can integrate the new laser pointer I fitted today ::):

**Comment by phillc54** [comment]
I am part way through rs485 now, when that is done I think user buttons are next on the agenda.

**Comment by rodw-au** [comment]
Sounds good. When we have user buttons we will be good to go here then. 

I have a LCNC friend here who has agreed to design a circuit board that will act as a shield for a 7i73 that breaks out the connectors  and also have a header to connect an Odroid H2+ which will have a RS485 on the board (from one of the Odroid Uarts) so that will be cool when its done!

I'm holding him up right now... but we met to discuss it last week. He wants some more info from me.
