### ISSUE TITLE
Material needs to be displayed on the front screen

### ISSUE THREAD

**Issue by rodw-au** [phillc54/qtplasmac#8]
We should not be forced to click to another screen to see what material we have configured. I often check this on a dry run. Maybe I have set up on 3 mm to cut a file on 2mm so I can check that sort of thing.
It needs to be refreshed as it changes during a run for spotting engraving etc.

**Comment by phillc54** [comment]
The active material is displayed above the preview

**Comment by rodw-au** [comment]
Cool, Now I've also found the file name!

**Comment by rodw-au** [comment]
Closed
